// Mock data for Metin2UP clone

export const navLinks = [
  { label: 'Anasayfa', href: '/', active: true },
  { label: 'Metin2 Pvp Sunucular', href: '/sunucular', icon: 'server' },
  { label: 'Açılacak PvP Serverler', href: '/acilacak', icon: 'megaphone' },
  { label: 'Rütbe Sistemi', href: '/rutbe' },
  { label: 'Reklam', href: '/reklam', highlight: true },
];

export const sideBanner = {
  image: 'https://www.metin2up.com/wp-content/uploads/2026/04/m2.png',
  title: 'METIN2UP',
  subtitle: 'BU ALANA REKLAM VEREBİLİRİNİZ!',
  contact: 'Reklam için iletişim',
  discord: 'Discord; discord.gg/metin2up',
};

export const vipTopics = [
  {
    id: 1,
    title: 'Metin2 Sohbet Grubu – Facebook Grubu',
    author: 'Metin2UP',
    authorAvatar: 'https://www.metin2up.com/wp-content/uploads/2025/06/33-1.png',
    replies: 2,
    views: 874,
    lastReply: { user: 'Server Tanıtım', text: 'katıldık', avatar: 'https://www.metin2up.com/wp-content/uploads/2026/04/images.png' },
    verified: true,
  },
  {
    id: 2,
    title: 'M2LODOS 1-105 ORTA EMEK – 26 HAZİRAN AÇILIYOR!',
    author: 'M2 Lodos',
    authorAvatar: 'https://www.metin2up.com/wp-content/uploads/2026/06/Logo2.png',
    replies: 0,
    views: 33,
    lastReply: null,
    verified: true,
  },
];

export const forumCategories = [
  {
    id: 'emek',
    title: 'Metin2 Emek Server Kategorisi',
    description: 'Ücretsiz Konu Paylaşım Alanıdır.',
    icon: 'https://www.metin2up.com/wp-content/uploads/2026/04/m2.png',
    subForums: [
      {
        id: 'sf-1-105',
        name: '1-105 Metin2 Serverler',
        description: '1-105 Sunucuları içeriden takip edebilirsiniz. Üye olarak konu açabilirsiniz.',
        topics: 77,
        replies: 58,
        lastPost: { title: 'LotusMt2 1-105 Orta Emek / 27 ŞUBAT Açılıyor!', user: 'Kaptan Mikro', avatar: 'https://www.metin2up.com/wp-content/uploads/2025/07/466380737_8787871551252117_7775012415435230135_n.jpg', verified: true },
      },
      {
        id: 'sf-1-120',
        name: '1-120 Metin2 Serverler',
        description: '1-120 Sunucuları içeriden takip edebilirsiniz. Üye olarak konu açabilirsiniz.',
        topics: 46,
        replies: 21,
        lastPost: { title: 'Metius2 1-120 Mobil Oyun – 29 Mayıs Açılıyor!', user: 'Metius2 Mobil', avatar: 'https://www.metin2up.com/wp-content/uploads/2026/05/metiusLogo1.png', verified: true },
      },
      {
        id: 'sf-1-99',
        name: '1-99 Metin2 Serverler',
        description: '1-99 Sunucuları içeriden takip edebilirsiniz. Üye olarak konu açabilirsiniz.',
        topics: 275,
        replies: 184,
        lastPost: { title: 'Açılış 14 Mart Cumartesi 21:00 1-99 Oto avsız orta emek server', user: 'ahmet arslan', avatar: '', verified: false },
      },
      {
        id: 'sf-global',
        name: 'Metin2 Global Serverler',
        description: 'You can follow Global servers from the inside. By becoming a member, you can create topics.',
        topics: 16,
        replies: 3,
        lastPost: { title: 'Aelys2 Fury 1-105 Global 22.05.2026', user: 'Aelys2 global', avatar: 'https://www.metin2up.com/wp-content/uploads/2026/05/Aelys2-1770140627-mobile.jpg', verified: true },
      },
    ],
  },
  {
    id: 'kolay',
    title: 'Metin2 Kolay Server Kategorisi',
    description: 'Ücretsiz Konu Paylaşım Alanıdır.',
    icon: 'https://www.metin2up.com/wp-content/uploads/2026/04/m2.png',
    subForums: [
      {
        id: 'sf-55-120',
        name: '55-120 Metin2 Serverler',
        description: '55-120 Sunucuları içeriden takip edebilirsiniz. Üye olarak konu açabilirsiniz.',
        topics: 60,
        replies: 54,
        lastPost: { title: 'Pitaya2 55-120 New School – 19 Haziran Açılıyor !', user: 'Pitaya2 55-120', avatar: 'https://www.metin2up.com/wp-content/uploads/2026/06/PitayaSunucuProfil-1.gif', verified: true },
      },
      {
        id: 'sf-65-250',
        name: '65-250 Metin2 Serverler',
        description: '65-250 Sunucuları içeriden takip edebilirsiniz. Üye olarak konu açabilirsiniz.',
        topics: 78,
        replies: 46,
        lastPost: { title: 'AtakMt2 70-250 Orta Emek / 12 Haziran Açılıyor!', user: 'Atak Metin2', avatar: 'https://www.metin2up.com/wp-content/uploads/2026/06/6a25e35154fc69.07999907_lpnjeoiqfkmhg.png', verified: true },
      },
      {
        id: 'sf-wslik',
        name: 'Wslik Metin2 Serverler',
        description: 'Wslik Sunucuları içeriden takip edebilirsiniz. Üye olarak konu açabilirsiniz.',
        topics: 65,
        replies: 60,
        lastPost: { title: 'Yeni VslikMt2 Hem Vslik/Farm Yapısı İle 19 Haziran Cuma Günü Saat 21.00\'da Açılıyor.', user: 'Pangan ESTR', avatar: 'https://www.metin2up.com/wp-content/uploads/2026/02/1e3c61649a8ac7ec575fe2cf24d82a01.jpg', verified: false, isNew: true },
      },
    ],
  },
  {
    id: 'hata',
    title: 'Hata Çözümleri ve Destek',
    description: 'Hata Çözümleri ve Destek Paylaşım Alanı',
    icon: 'https://www.metin2up.com/wp-content/uploads/2025/06/333-1.png',
    subForums: [
      {
        id: 'sf-diger',
        name: 'Diğer Çözümler',
        description: '',
        topics: 32,
        replies: 11,
        lastPost: { title: 'Metin2 Tüm "SYSSER" Hataları ve Çözümleri', user: 'omer ro', avatar: '', verified: false },
      },
      {
        id: 'sf-hatalar',
        name: 'Hata Çözümleri',
        description: 'Hata Çözümleri Paylaşım Alanı.',
        topics: 41,
        replies: 18,
        lastPost: { title: 'Monitöre görüntü gelmiyorsa ne yapılması gerekir?', user: 'ufuk erte', avatar: '', verified: false },
      },
    ],
  },
  {
    id: 'genel',
    title: 'Metin2 Genel',
    description: '',
    icon: 'https://www.metin2up.com/wp-content/uploads/2025/06/333-1.png',
    subForums: [
      {
        id: 'sf-grafik',
        name: 'Grafik - Tasarım - Video',
        description: 'Tasarımcı Paylaşım Alanı',
        topics: 10,
        replies: 6,
        lastPost: { title: 'Metin2 Grafik Tasarım Her Türlü Grafik Hizmetleriniz Yapılır Uygun Fiyattan', user: 'kingofwicker Design', avatar: '', verified: false },
      },
      {
        id: 'sf-lonca',
        name: 'Lonca Tanıtımı',
        description: 'Metin2 Lonca Tanıtım Bölgesi',
        topics: 20,
        replies: 14,
        lastPost: { title: 'ABSORBE EKİBİ +40 KADROSU İLE DEVAM ALIMLAR ACIK TS3 !', user: 'Metin2UP', avatar: 'https://www.metin2up.com/wp-content/uploads/2025/06/33-1.png', verified: true },
      },
      {
        id: 'sf-sohbet',
        name: 'Metin Sohbet - Tartışma Alanı',
        description: 'Metin2 Sohbet ve Tartışma Konu Alanı',
        topics: 15,
        replies: 16,
        lastPost: { title: '2009 Yılında Metin2 Oynardım', user: 'Zor Yol', avatar: '', verified: false },
      },
      {
        id: 'sf-wiki',
        name: 'Metin2 Wiki & Oyun Kılavuzu',
        description: 'Metin2 oyuncuları için görevler, itemler, farm ve level kasma rehberi: Metin2 Wiki & Oyun Kılavuzu.',
        topics: 120,
        replies: 16,
        lastPost: { title: 'Büyülü Orman ve Jotun Thrym Solo Kesim Rehberi', user: 'co muro', avatar: 'https://www.metin2up.com/wp-content/uploads/2026/01/s-9ebfc5d8842e456f728965c8083f1f177c2e2e04.jpg', verified: false },
      },
    ],
  },
  {
    id: 'developer',
    title: 'Metin2 Developer Kategorisi',
    description: '',
    icon: 'https://www.metin2up.com/wp-content/uploads/2025/06/333-1.png',
    subForums: [
      {
        id: 'sf-python',
        name: 'C++ / C# / Python Kodlama',
        description: '',
        topics: 9,
        replies: 6,
        lastPost: { title: 'Metin2 – Site Domainler Satılıktır !', user: 'Metin2UP', avatar: 'https://www.metin2up.com/wp-content/uploads/2025/06/33-1.png', verified: true },
      },
      {
        id: 'sf-gm',
        name: 'Metin2 GM Kodları',
        description: 'Metin2 GM Kodlarına Burdan Bakabilirsiniz - Metin2UP',
        topics: 36,
        replies: 17,
        lastPost: { title: 'Çiftel Silah Kodları', user: 'Metin2UP Moderetor', avatar: 'https://www.metin2up.com/wp-content/uploads/Logo-Saydam-Kopya.png', verified: true },
      },
      {
        id: 'sf-quest',
        name: 'Metin2 PvP Quest Paylaşımları',
        description: 'Metin2 PvP Quest Konu Alanı',
        topics: 6,
        replies: 3,
        lastPost: { title: 'Boss Notice Bilgi Questi', user: 'emre martın', avatar: 'https://www.metin2up.com/wp-content/uploads/2026/04/images.jpg', verified: false },
      },
      {
        id: 'sf-files',
        name: 'Metin2 PvP Serverler Files',
        description: 'Metin2 PvP Serverler Files Kategori Alanı',
        topics: 9,
        replies: 11,
        lastPost: { title: 'BGAME WORKS İLE FİLES HİZMETİ', user: 'EMİR Ertürk', avatar: '', verified: true },
      },
    ],
  },
  {
    id: 'video',
    title: 'Video ve Yayın Kanal Tanıtımları',
    description: 'İçerik Üreticisi İçin Açılmış Üçretsiz Konu Paylaşım alanıdır.',
    icon: 'https://www.metin2up.com/wp-content/uploads/2025/07/icons8-video-call-48.png',
    subForums: [
      {
        id: 'sf-tiktok',
        name: 'Tiktok Kanalı Tanıtımları',
        description: 'Tiktok Yayınızı ve Kendiniz Hakkında Konu Paylaşım Alanıdır.',
        topics: 7,
        replies: 6,
        lastPost: { title: 'Begumistan Tiktok Metin2 Yayıncısı', user: 'Begumistan Begumistan', avatar: 'https://www.metin2up.com/wp-content/uploads/2026/06/WhatsApp_Image_2026-05-05_at_19.19.091-2.jpeg', verified: false },
      },
      {
        id: 'sf-yt',
        name: 'Youtube Kanal Tanıtımları',
        description: 'Youtube Yayınızı ve Kendiniz Hakkında Konu Paylaşım Alanıdır.',
        topics: 8,
        replies: 3,
        lastPost: { title: 'Maykre Metin2 Partner', user: 'Maykre Partner', avatar: 'https://www.metin2up.com/wp-content/uploads/2026/04/logo-1.png', verified: false },
      },
    ],
  },
];

export const stats = {
  totalTopics: 1052,
  totalReplies: 728,
  totalMembers: 3247,
  newestMember: 'gameroglu',
};
